CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Email nvarchar(100) NOT NULL,
	Password nvarchar(100) NOT NULL,
	Salt nvarchar(200) NOT NULL,
	FirstName nvarchar(100),
	LastName nvarchar(100),
	CreatedAt DATETIME NOT NULL
);

CREATE TABLE Animals (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	Name nvarchar(100) NOT NULL,
	YearOfBirth int NOT NULL
);

CREATE TABLE AnimalsToCare (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	AnimalId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	DateFrom DATETIME NOT NULL,
	DateTo DATETIME NOT NULL,
	IsTaken bit NOT NULL
);